# app.yaml

runtime: python39

entrypoint: gunicorn -b :$PORT main:app

instance_class: F2

env_variables:
  MAX_CONTENT_LENGTH: 1048576
  UPLOAD_FOLDER: './uploads'
  RECAPTCHA_SITE_KEY: '6Lcdxj0mAAAAANnD4oSa0nSbrJW9xRjhtBqklmf1'
